apiVersion: v1
baseDomain: customer.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: mycluster
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  vsphere:
    apiVIP: 192.168.14.75
    cluster: testcluster
    datacenter: DC01
    defaultDatastore: datastore1
    ingressVIP: 192.168.14.76
    network: VM Network
    password: Sh@r@d123$
    username: administrator@myvcenter.local
    vCenter: 192.168.14.100
publish: External
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K3NoYXJhZGlibTFhbG1xOWtlcXlhY3lzNGJlMDJ1dmtqOHZxbzoyVENWNjVPRkhQUURHNFNHQlFNU0gwSEwxNkFYSVIyVEtBSkIwSk1XSjlBWFVROTlWODU0N0xHVTFRT0dWNE1K","email":"schandr1@in.ibm.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K3NoYXJhZGlibTFhbG1xOWtlcXlhY3lzNGJlMDJ1dmtqOHZxbzoyVENWNjVPRkhQUURHNFNHQlFNU0gwSEwxNkFYSVIyVEtBSkIwSk1XSjlBWFVROTlWODU0N0xHVTFRT0dWNE1K","email":"schandr1@in.ibm.com"},"registry.connect.redhat.com":{"auth":"NTMzNTAwODV8dWhjLTFhbE1ROWtlUVlhY3lzNGJlMDJVdktqOHZxbzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmpOMkptTVdVMk1EWmpObUUwT1dJellUazJaVFkwTVRSa01EbGlNamRoTkNKOS5uc0VQMEpTN3VZV1NzRkstZXJpMUVUVHZuck5wU0hDLVI2cmtyUmJBMndCbnVtanhNLUVnWEZnNTlSc2stQU5sZDBmTFVhMzZLb2lhaGstTnE4YnpVRWVZaHQ0NjhacS1yendLMzRtUjcxNlB3RFFRYzlKczNybGZzbHcxanY5SjdiZGpTUzJFNV85Z0dzeW5kN25rM2hKMUNzUk45dkNnbmpNc1dCTG9falFEb1BTMGxWb0Y1eWJBVFlCQVIwUzhoajdQTk1DQ2Y5VWpZX0MxekNMRGtZNS1lZVFzeHRwV3dlWTNLajdZM2tTMzhHSjk3SFl1b2RYYldwSTNyQk85N3RXR3c3V0pOc05QRDZwbHRsb2hVMjl6RUphU1Z3UDJCQmVzZHFMc0FNY09lZVBRVGVmU1hIVU9uWnM4akJ1WGFpR2NCWURCUE5SYnZ3T3RMMXFiX3hDN256RHRZTDB1RGpkNzlnT0VUZXYyUnREVXUxeDJGUzdTRDd1Rmx2RDFtVUwxdjhMc290TFJXU0hVQko5VU5TUG9BYXZQQlFLVHM2OHpNSlMwVk8wYjhWSnJ5WnRLNGV2cXVZMG5CaXV5OHo5YlEwV2x6c191cUdFSkRrZVlZRmxocW8teGNJeUs4RllCa0c3X0ZoUDdaWGYtSU9rQ0dlQ3p4OWpKWFhpVnpuTjkzSHZzdEJUdU9LYVJVRnF5aTcyMllFSTZoR010NlFRSzl1emRVZWJDZGZsODNWdEU5WHlrTjVOZ3U5LS1Zdy1YN3ZOMDVaNHpDVkFQTFdLOS12OXFVR0V5b1ZPc2hzejN4VlprdzQyRHlad095VnRPSmJiQktXQWlBUGZIZE40NElPdDFTaHlJS0k2SFNabzBiSkwyNFJwbTFvelF6TGxnbFEzazVDYw==","email":"schandr1@in.ibm.com"},"registry.redhat.io":{"auth":"NTMzNTAwODV8dWhjLTFhbE1ROWtlUVlhY3lzNGJlMDJVdktqOHZxbzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmpOMkptTVdVMk1EWmpObUUwT1dJellUazJaVFkwTVRSa01EbGlNamRoTkNKOS5uc0VQMEpTN3VZV1NzRkstZXJpMUVUVHZuck5wU0hDLVI2cmtyUmJBMndCbnVtanhNLUVnWEZnNTlSc2stQU5sZDBmTFVhMzZLb2lhaGstTnE4YnpVRWVZaHQ0NjhacS1yendLMzRtUjcxNlB3RFFRYzlKczNybGZzbHcxanY5SjdiZGpTUzJFNV85Z0dzeW5kN25rM2hKMUNzUk45dkNnbmpNc1dCTG9falFEb1BTMGxWb0Y1eWJBVFlCQVIwUzhoajdQTk1DQ2Y5VWpZX0MxekNMRGtZNS1lZVFzeHRwV3dlWTNLajdZM2tTMzhHSjk3SFl1b2RYYldwSTNyQk85N3RXR3c3V0pOc05QRDZwbHRsb2hVMjl6RUphU1Z3UDJCQmVzZHFMc0FNY09lZVBRVGVmU1hIVU9uWnM4akJ1WGFpR2NCWURCUE5SYnZ3T3RMMXFiX3hDN256RHRZTDB1RGpkNzlnT0VUZXYyUnREVXUxeDJGUzdTRDd1Rmx2RDFtVUwxdjhMc290TFJXU0hVQko5VU5TUG9BYXZQQlFLVHM2OHpNSlMwVk8wYjhWSnJ5WnRLNGV2cXVZMG5CaXV5OHo5YlEwV2x6c191cUdFSkRrZVlZRmxocW8teGNJeUs4RllCa0c3X0ZoUDdaWGYtSU9rQ0dlQ3p4OWpKWFhpVnpuTjkzSHZzdEJUdU9LYVJVRnF5aTcyMllFSTZoR010NlFRSzl1emRVZWJDZGZsODNWdEU5WHlrTjVOZ3U5LS1Zdy1YN3ZOMDVaNHpDVkFQTFdLOS12OXFVR0V5b1ZPc2hzejN4VlprdzQyRHlad095VnRPSmJiQktXQWlBUGZIZE40NElPdDFTaHlJS0k2SFNabzBiSkwyNFJwbTFvelF6TGxnbFEzazVDYw==","email":"schandr1@in.ibm.com"}}}'
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCnY0BITFTZWGclX2XYbUIEPa3ChlO13uEWueBz4HhjNj8WUd/bBS28omP9IrecG1LC4aHVtovXuq4PhkQyF6ErcFKlXuOt3BaRYdnuHRo+L+CkKXqFHb/w2fN+asmQzcQc82J7n7m7opykATSavHGnosHVeZ/pdya2fiiyklTbZPxeRQs7bJ2Pb42Ugxq4X3/WMa1ZWHmBIlSQdXG5vBNQ1M0DoKjeZipXMTGVSrLINS3Ym4OJZ4izSh1CpFhU4TWC96QYtD+9NJNUTpE9Db5RXudD5W5VDAC4eqR0416qHq8psMTTqPHqYpIAxgFIMXA2/BcgZfjPs9u31Q+UysU5 root@bastion.mycluster.test.example.com'